# ============LICENSE_START=======================================================
# org.onap.dcae
# ================================================================================
# Copyright (c) 2018 AT&T Intellectual Property. All rights reserved.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================
FROM busybox
RUN mkdir -p /opt/tls/source && mkdir -p /opt/tls/shared
COPY ./tls /opt/tls/source
RUN base64 -d /opt/tls/source/trust.jks.b64 > /opt/tls/source/trust.jks  && base64 -d /opt/tls/source/cert.jks.b64 > /opt/tls/source/cert.jks && base64 -d /opt/tls/source/cert.p12.b64 > /opt/tls/source/cert.p12
COPY setup-tls.sh /opt/tls
ENTRYPOINT  ["/opt/tls/setup-tls.sh"]
