# ============LICENSE_START=======================================================
# org.onap.dcae
# ================================================================================
# Copyright (c) 2018 AT&T Intellectual Property. All rights reserved.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================
#
# ECOMP is a trademark and service mark of AT&T Intellectual Property.
FROM cloudifyplatform/community:cloudify-manager-18.2.28
MAINTAINER maintainer

ENV TYPE_REPO {{ ONAPTEMPLATE_RAWREPOURL_org_onap_dcaegen2_platform_plugins_releases }}
ENV CCSDK_REPO {{ ONAPTEMPLATE_RAWREPOURL_org_onap_ccsdk_platform_plugins_releases }}

# Store type files locally
RUN mkdir scripts
COPY get-type-files.sh scripts
# Load our type files and the Cloudify 3.4 type files
RUN scripts/get-type-files.sh ${TYPE_REPO} ${CCSDK_REPO}\
    && mkdir /opt/manager/resources/spec/cloudify/3.4\
    && curl -Ss https://cloudify.co/spec/cloudify/3.4/types.yaml > /opt/manager/resources/spec/cloudify/3.4/types.yaml\
    && chown -R cfyuser:cfyuser /opt/manager/resources/spec/cloudify/3.4
# Create mount point for CM config file
RUN mkdir -p /opt/onap && chown cfyuser:cfyuser /opt/onap

# For HEAT environment, install software needed to use Cloudify CLI 4.2 to install plugins & deploy blueprints locally
# Install python development-related packages
RUN yum install -y gcc python-devel python-virtualenv python-pip

# Set up virtualenv and install Cloudify CLI 4.2
RUN pip install --upgrade pip==9.0.3 \
    && virtualenv cfy42 \
    && source cfy42/bin/activate \
    && pip install cloudify==4.2
